updated sample to use the 2.0 liberty plugin
mattbsox/sample.javaee7.jms pull request #1
Opened 2017-05-16 20:18 UTC by mattbsox

2017-05-26 18:06 UTC, patricktiu requested changes

2017-05-26 18:06 UTC, patricktiu commented on README.md
> +This project can be built with [Apache Maven](http://maven.apache.org/). The project uses [Liberty Maven Plug-in](https://github.com/WASdev/ci.maven) to automatically download and install Liberty pro
nstruction for **Running with Maven running** in README.md 

This project can be built with Apache Maven. The project uses [Liberty Maven Plug-in](https://github.com/WASdev/ci.maven) to automatically download and install Liberty ~~profile~~ `with Java EE7 Full Platform`  runtime from the ~~Liberty repository~~ `Maven Central`. Liberty Maven Plug-in is also used to create, configure, and run the application on the Liberty server.

2017-05-26 18:06 UTC, patricktiu commented on README.md
> +This project can be built with [Apache Maven](http://maven.apache.org/). The project uses [Liberty Maven Plug-in](https://github.com/WASdev/ci.maven) to automatically download and install Liberty pro
We need to update the instruction of **Running in Eclipse**.  


1.    Download and install Eclipse with the WebSphere Developer Tools.
2.   ~~Create a new Liberty Profile Server.~~
3.    Clone this repository.
4.    Import the sample into Eclipse using File -> Import -> Maven -> Existing Maven Projects option.
5.    ~~Edit the server.xml file located in the Servers -> DefaultServer folder in EnterpriseExporer. Copy the server.xml features from this project, found under the <featureManager> in /src/main/wlp/server.xml~~
6.   ~~Deploy the sample into Liberty server.~~ Right click on the project and select Run As -> Run on Server option. Find and select the Liberty profile server and press Finish.
7.    Go to: http://localhost:9080/sample.javaee7.jms/

2017-05-26 18:06 UTC, patricktiu commented on src/main/wlp/server.xml
> -       <feature>jms-2.0</feature>
Did you accidentally remove the jms-2.0 feature?

2017-05-26 18:06 UTC, patricktiu commented on pom.xml
> -        <finalName>${project.artifactId}</finalName>
Other samples are using `<finalName>`.  Let's continue to use it.

2017-05-26 18:06 UTC, patricktiu commented on pom.xml
> +                    <stripVersion>true</stripVersion>
You can delete line 58. The `<stripVersion>` is not in the liberty-maven-app-parent pom

2017-05-26 18:06 UTC, patricktiu commented on pom.xml
> +                        <appLocation>${project.artifactId}.war</appLocation>
change to `<appLocation>${project.build.finalName}.war</appLocation>`

2017-05-26 18:29 UTC, mattbsox commented on pom.xml
> +                        <appLocation>${project.artifactId}.war</appLocation>
Should I go change this in the rest of the samples as well?

2017-05-26 18:31 UTC, mattbsox commented on src/main/wlp/server.xml
> -       <feature>jms-2.0</feature>
Ya, that was an accident. I'll add it back.

2017-05-26 18:55 UTC, mattbsox commented on src/main/wlp/server.xml
> -       <feature>jms-2.0</feature>
Do the wasJmsClient-2.0 and wasJmsServer-1.0 take care of the jms-2.0 feature? I think that's why I took it out in the first place. https://www.ibm.com/support/knowledgecenter/SSAW57_liberty/com.ibm.websphere.wlp.nd.multiplatform.doc/ae/twlp_msg.html

2017-05-30 21:45 UTC, mattbsox commented on src/main/wlp/server.xml
> -       <feature>jms-2.0</feature>
We determined that wasJmsServer and wasJmsClient both pull in the jms-2.0 feature when they are installed, so it doesn't need to be set as a feature.

2017-05-31 14:25 UTC, patricktiu approved these changes

2017-06-06 01:45 UTC, patricktiu approved these changes

2017-06-06 15:22 UTC, merged